storage:
  tsdb:
    out_of_order_time_window: 10m

otlp:
  promote_resource_attributes: ["env", "service.name"]

remote_write:
  - url: http://0.0.0.0:9090/api/v1/otlp/v1/metrics
    queue_config:
      capacity: 1000000
      batch_send_deadline: 10s
      max_samples_per_send: 1000
      max_shards: 3
    remote_timeout: "30s"
    follow_redirects: true