{
 "title": "Demo dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory usage (after GC)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (service_name) (jvm_memory_used_after_last_gc_bytes) / sum by (service_name) (jvm_memory_limit_bytes)",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "sum by (service_name) (jvm_memory_heap_used_by)/ sum by (service_name) (jvm_memory_heap_max_by)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (jvm_cpu_recent_utilization_ratio)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "HTTP response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (http_route, error_type, le)(rate(http_server_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95 {{http_route}}"
    }
   ]
  },
  {
   "title": "Incoming HTTP requests - throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_route, error_type) (rate(http_server_request_duration_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Kafka request latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(kafka_producer_request_latency_max)",
     "legendFormat": "producer request latency: max"
    },
    {
     "expr": "avg(kafka_producer_request_latency_avg)",
     "legendFormat": "producer request latency: avg"
    },
    {
     "expr": "max(kafka_consumer_fetch_latency_max)",
     "legendFormat": "consumer fetch latency: max"
    },
    {
     "expr": "avg(kafka_consumer_fetch_latency_avg)",
     "legendFormat": "consumer fetch latency: avg"
    },
    {
     "expr": "max(kafka_consumer_commit_latency_max)",
     "legendFormat": "commit latency: max"
    },
    {
     "expr": "avg(kafka_consumer_commit_latency_avg)",
     "legendFormat": "commit latency avg"
    }
   ]
  },
  {
   "title": "Kafka client throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_producer_record_send_rate)",
     "legendFormat": "send record rate {{topic}}"
    },
    {
     "expr": "sum by (topic) (kafka_consumer_records_consumed_rate)",
     "legendFormat": "consume record rate {{topic}}"
    },
    {
     "expr": "sum (kafka_consumer_commit_rate)",
     "legendFormat": "commit rate {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max(kafka_consumer_records_lag_max)",
     "legendFormat": "max lag"
    },
    {
     "expr": "avg(kafka_consumer_records_lag_avg)",
     "legendFormat": "avg lag"
    }
   ]
  }
 ]
}